title: "Occasionally clever"
url: https://patrick-nicholson.github.io
baseurl: /

author:
  name: "Patrick Nicholson"
  url: https://github.com/patrick-nicholson

paginate: 20

github:
  repo: https://github.com/patrick-nicholson/patrick-nicholson.github.io/

permalink: pretty
