services:

  jupyter_sql:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - "${PWD}:/home/jovyan/work"
    networks:
      - nilsson

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - nilsson
    restart: always

networks:
  nilsson:
    driver: bridge